name       : duckmarines
version    : 1.0c
release    : 1
source     :
    - https://github.com/SimonLarsen/duckmarines/releases/download/v1.0c/duckmarines-1.0c.love : 09eaf2365cde378737898e04453a933ea1a334b4932cee08833f4112f7bc6fe7
license    :
    - BSD-3-Clause
    - CC-BY-SA-4.0
    - CC-BY-NC-ND-4.0
component  : games.arcade
summary    : Duck Marines is a cross-platform free software remake of Sonic Team's Chu ChuRocket for the Sega Dreamcast.
description: |
    Duck Marines is a cross-platform free software remake of Sonic Team's Chu ChuRocket for the Sega Dreamcast.
extract    : no
rundeps    :
    - love
install    : |
    install -D -m 00644 $pkgfiles/duckmarines.desktop $installdir/usr/share/applications/duckmarines.desktop
    install -D -m 00644 $sources/duckmarines-$version.love $installdir/usr/share/duckmarines/duckmarines.love
